name: Docker Hardfork CI

on:
  push:
    branches:
    - 'develop'
    - 'release_hf_*'
    paths:
      - 'libraries/chain/hardfork.d/*'
      - '.github/workflows/docker-hardfork-ci.yml'


jobs:
  build-testnet:
    runs-on: self-hosted

    if: github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        echo "Building testnet image"

    - name: Export variables
      run: |
        rm libraries/chain/hardfork.d/0-preamble.hf
        echo "HF_VERSION=$(ls libraries/chain/hardfork.d | tr -d '.hf' | tr -d '0_' | sort -nr | head -n1)" >> $GITHUB_ENV
        echo "GIT_COMMIT=$(git rev-parse --short HEAD || echo "GitNotFound")" >> $GITHUB_ENV
        echo "LIVE_TESTNET=ON" >> $GITHUB_ENV
        echo "NET_NAME=testnet" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build \
        --build-arg BRANCH_NAME=testnet \
        --build-arg GIT_COMMIT=${GIT_COMMIT} \
        --build-arg LIVE_TESTNET=${LIVE_TESTNET} \
        --build-arg BUILD_VERSION=0.${HF_VERSION}.0.${GIT_COMMIT} \
        -t "scorum/${NET_NAME}:0.${HF_VERSION}.0.${GIT_COMMIT}" .

    - name: Push docker image to registry
      run: docker push scorum/${NET_NAME}:0.${HF_VERSION}.0.${GIT_COMMIT}

  build-mainnet:
    runs-on: self-hosted

    if: startsWith(github.ref, 'refs/heads/release_hf_')

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        echo "Building mainnet image"

    - name: Export variables
      run: |
        rm libraries/chain/hardfork.d/0-preamble.hf
        echo "HF_VERSION=$(ls libraries/chain/hardfork.d | tr -d '.hf' | tr -d '0_' | sort -nr | head -n1)" >> $GITHUB_ENV
        echo "GIT_COMMIT=$(git rev-parse --short HEAD || echo "GitNotFound")" >> $GITHUB_ENV
        echo "LIVE_TESTNET=OFF" >> $GITHUB_ENV
        echo "NET_NAME=release" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build --build-arg LIVE_TESTNET="${LIVE_TESTNET}" -t "scorum/${NET_NAME}:0.${HF_VERSION}.0.${GIT_COMMIT}" .

    - name: Push docker image to registry
      run: docker push scorum/${NET_NAME}:0.${HF_VERSION}.0.${GIT_COMMIT}
